# Generated by Django 3.2.12 on 2022-03-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomModel',
        ),
    ]
