# Generated by Django 3.2.12 on 2022-03-23 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220323_1803'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0002_alter_rating_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(choices=[(1, 'Ненависть'), (2, 'Неприязнь'), (
                3, 'Нейтрально'), (4, 'Обожание'), (5, 'Любовь')], null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
