# Generated by Django 3.2.12 on 2022-03-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20220323_1803'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
