# Generated by Django 3.2.12 on 2022-04-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_auto_20220324_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.IntegerField(choices=[(0, 'Оценка отсутствует'), (1, 'Ненависть'), (2, 'Неприязнь'), (3, 'Нейтрально'), (4, 'Обожание'), (5, 'Любовь')], null=True, verbose_name='Оценка'),
        ),
    ]
