# Generated by Django 3.2.12 on 2022-04-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20220413_1829'),
        ('rating', '0007_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raiting', to='catalog.item', verbose_name='Товар'),
        ),
    ]
