# Generated by Django 3.2.12 on 2022-03-22 10:28

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True,
                 serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.TextField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile(
                    '^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('weight', models.PositiveIntegerField(default=100, validators=[
                 django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32767)])),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True,
                 serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=True)),
                ('slug', models.TextField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile(
                    '^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True,
                 serialize=False, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_published', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150)),
                ('text', models.TextField(validators=[
                 catalog.validators.validate_text])),
                ('category', models.ForeignKey(blank=True, null=True,
                 on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('tags', models.ManyToManyField(blank=True, to='catalog.Tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
