# Generated by Django 3.2.12 on 2022-03-23 15:03

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20220323_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(
                default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(
                blank=True, to='catalog.Tag', verbose_name='теги'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(
                validators=[catalog.validators.validate_text], verbose_name='Описание'),
        ),
    ]
