# Generated by Django 3.2.12 on 2022-04-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220325_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(
                default='', max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(
                default='', max_length=150, verbose_name='Название'),
        ),
    ]
